application: nemu-io
version: 1
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: web/css
  
- url: /images
  static_dir: web/images

- url: /favicon.ico
  static_files: web/images/favicon.ico
  upload: web/images/favicon\.ico
  mime_type: image/x-icon

- url: /js
  static_dir: web/js

- url: /config
  script: main.py
  secure: always
  login: admin
  
- url: /home
  script: main.py
  login: admin
  
- url: /oauth/(.*)/(.*)
  script: twitter_oauth_handler.py
  login: admin

- url: /cron/.*
  script: main.py
  login: admin

- url: /.*
  script: main.py